platform: linux

sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 7.3
    - php: 7.4
  allow_failures:
    - php: 7.4

branches:
  only:
    - master
    - develop
    - /^feature\/.*$/
    - /^bugfix\/.*$/

cache:
  directories:
    - $HOME/.composer/cache
    - ./bin/.phpunit

before_install:
  - composer self-update
  - composer validate --no-check-publish

install:
  - composer install

script:
  - composer test

notifications:
  email: false
