platform: linux
sudo: false
language: php
php:
    - '7.3'
cache:
    directories:
        - $HOME/.composer/cache/files
        - ./bin/.phpunit
install:
    - composer install
script:
    - composer test
notifications:
    email: false
