version: '3.7'

services:

    mysql:
        image: mysql:5.7
        container_name: muzirus_mysql
        restart: always
        volumes:
            - ./docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: muzirus
            MYSQL_USER: muzirus
            MYSQL_PASSWORD: muzirus
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: muzirus_phpmyadmin
        restart: always
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql
        depends_on:
            - mysql

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: muzirus_php
        restart: always
        volumes:
            - .:/usr/src/muzirus
            - ./vendor:/usr/src/muzirus/vendor:cached
        env_file:
            - .env
        user: 1000:1000

    nginx:
        image: nginx:1.17.3-alpine
        container_name: muzirus_nginx
        restart: always
        volumes:
            - .:/usr/src/muzirus
            - ./vendor:/usr/src/muzirus/vendor:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 80:80
        depends_on:
            - php
            - mysql
