version: '3.3'
services:
#  nginx-proxy:
#    image: jwilder/nginx-proxy
#    ports:
#      - 80:80
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock:ro
#    environment:
#      DEFAULT_HOST: dictionary.lh
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    image: dictionary-app
    ports:
      - 80:80
    volumes:
      - .:/srv/app
#    environment:
#      VIRTUAL_HOST: dictionary.lh,*.dictionary.lh
#      VIRTUAL_PORT: 80
    links:
      - mysql
    depends_on:
      - mysql
#    environment:
#      DB_HOST: mysql
#      DB_DATABASE: dictionary
#      DB_USERNAME: docker_username
#      DB_PASSWORD: docker_password
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - .docker/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dictionary
      MYSQL_USER: docker_username
      MYSQL_PASSWORD: docker_password
      MYSQL_ROOT_PASSWORD: root
#      VIRTUAL_HOST: mysql.dictionary.lh
#      VIRTUAL_PORT: 3306
