version: '3.3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    image: dictionary-app
    ports:
      - 8080:80
    volumes:
      - ./.docker/app/php.ini:/usr/local/etc/php/php.ini:ro
      - .:/srv/app
    working_dir: /srv/app
    environment:
      TIMEZONE: Europe/Bratislava
      VIRTUAL_HOST: dictionary.lh,*.dictionary.lh
      VIRTUAL_PORT: 80
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dictionary
      MYSQL_USER: docker_username
      MYSQL_PASSWORD: docker_password
      MYSQL_ROOT_PASSWORD: root
      VIRTUAL_HOST: mysql.dictionary.lh
      VIRTUAL_PORT: 3306
