index:
    path: /
    controller: App\Controller\IndexController::index
    defaults:
        _locale: '%locale%'
app:
    prefix: /{_locale}
    resource: '../src/Controller'
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
logout:
    path: /logout
