index:
    path: /
    controller: App\Controller\IndexController::indexWithoutLocale
app:
    prefix: /{_locale}
    resource: '../src/Controller'
    requirements:
        _locale: '%app_locales%'
logout:
    path: /logout
